name: animated_digit
description: A scrolling digital animation widget that can be used to display the amount of animation, the number of people online in real-time, Any number that requires animation effects is simple and easy to use, and it can also guarantee the accuracy of the amount of calculation.
version: 1.0.4
homepage: https://github.com/mingsnx/animated_digit

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
