name: animated_digit
description: A scrolling digital animation widget that can be used to display the amount of animation.
version: 3.1.0
homepage: https://github.com/mingsnx/animated_digit

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
